### ISSUE TITLE
[Insight] The Symfony Dependency Injection Container should not be passed as an argument - in Datatable/View/AbstractDatatableView.php, line 93

### ISSUE THREAD

**Issue by stwe** [stwe/DatatablesBundle#130]
**[in Datatable/View/AbstractDatatableView.php, line 93](https://github.com/stwe/DatatablesBundle/blob/55cac8b559605d2f8d428591e2a3f6b03d5ebf51/Datatable/View/AbstractDatatableView.php#L93)**

> A Symfony dependency injection container has been found as an argument.

```php
     * Ctor.
     *
     * @param ContainerInterface $container            The service container
     * @param array              $defaultLayoutOptions The default layout options
     */
    public function __construct(ContainerInterface $container, array $defaultLayoutOptions)
    {
        $this->container = $container;

        $this->features = new Features();
        $this->options = new Options();
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/61803d08-17ab-4a69-ad13-6ec448762332/analyses/34)_

**Comment by DarekTw** [comment]
I think that previous separated services were good enough.
I added security because I cannot do this with my datatable service definition with custom argument
in
```
services:
    sg_datatables.post:
        class: AppBundle\Datatables\PostDatatable
        tags:
            - { name: sg.datatable.view }
```
