### ISSUE TITLE
Datatable service class

### ISSUE THREAD

**Issue by patie** [stwe/DatatablesBundle#19]
Hi,

what about registrating datatable class as service ?

In example i see only:

```
    sg_datatables.media:
        class: Component\MediaBundle\Datatable\MediaDatatable
        tags:
            - { name: sg.datatable.view }
```

there is no any registered service with name sg.datatable.view

but i have :

`class MediaDatatable extends AbstractDatatableView`

and AbstractDatatableView constructor looks like this:

`public function __construct(TwigEngine $templating, Translator $translator, RouterInterface $router, array $defaultLayoutOptions)`

so i give logicaly error like this:

```
An exception has been thrown during the rendering of a template ("Catchable Fatal Error: Argument 1 passed to Sg\DatatablesBundle\Twig\DatatableTwigExtension::datatableRender() must be an instance of Sg\DatatablesBundle\Datatable\View\AbstractDatatableView, null given .......
```

probably i missed something.. any idea please ? thx
