### ISSUE TITLE
Update translation files

### ISSUE THREAD

**Issue by stwe** [stwe/DatatablesBundle#270]
Some translation files are not up to date. 

- ~~messages.es.yml~~ ✓
- messages.fa.yml
- ~~messages.fr.yml~~ ✓
- ~~messages.it.yml~~ ✓
- ~~messages.nl.yml~~ ✓
- ~~messages.pl.yml~~ ✓
- ~~messages.ru.yml~~ ✓

***I have added the English translation as a placeholder .***

Many thanks.

**Comment by migmolrod** [comment]
Spanish translation 'on route'. Expect a PR soon.

**Comment by migmolrod** [comment]
Here it goes

**Comment by oidnus** [comment]
pl wait on pull request :smile:

**Comment by stwe** [comment]
@oidnus : Thanks.

please look at the messages.en.yml

can you also translate the following?

```
daterange:
    apply: "Apply"
    cancel: "Cancel"
    format: "YYYY-MM-DD"
editable:
    tableRedraw: "The changes relates multiple records. The table is redraw with the new data."
```
