### ISSUE TITLE
translation ORMBehaviors

### ISSUE THREAD

**Issue by fyher** [stwe/DatatablesBundle#275]
i have the translation table ORMBehaviors with filed and the filed return empty  with query can i check to return the filed translation ?

**Comment by stwe** [comment]
You have seen my [example](https://github.com/stwe/DatatablesBundle/blob/master/Resources/doc/translatable.md)?

You have updated your congif.yml?

```
# config.yml

sg_datatables:
    query:
        translation_query_hints: true
```

**Comment by fyher** [comment]
i see the exmaple thanks but i have update my code 

Unrecognized option "query" under "sg_datatables"

?

**Comment by stwe** [comment]
Try:

```
sg_datatables:
    datatable:
        query:
            translation_query_hints: true
```
