### ISSUE TITLE
Translations in datatable file

### ISSUE THREAD

**Issue by denya-vs** [stwe/DatatablesBundle#292]
In Datatable file(AppBundle/Datatables/*Datatable.php) locale not switched.
For example:
In this string I always get english text $this->translator->trans('datatables.actions.show').

**Comment by stwe** [comment]
try this in your config.yml:

```
framework:
    translator: { fallbacks: ["%locale%"] }

    # ...

    default_locale: "%locale%"
```
