### ISSUE TITLE
Use parent service instead of datatables tag

### ISSUE THREAD

**Issue by TobiasXy** [stwe/DatatablesBundle#322]
Currently my IDE is a bit confused about the datatable service definitions. It expects the classes to get a lot of arguments (i.e. all the arguments of the AbstractDatatableView class) but there a no arguments defined in the service definition, because they are later added by the DatatableViewPass.

I think (I may be wrong and there is a good reason for the current solution) it would be better to create a parent service (see here: http://symfony.com/doc/current/components/dependency_injection/parentservices.html) instead of adding the sg.datatable.view tag to all datatable services.

That way such a service definition would look like this:

```
app.datatable.entity:
    class: AppBundle\Datatables\EntityDatatable
    parent: sg.datatable.abstract
```

instead of

```
app.datatable.entity:
    class: AppBundle\Datatables\EntityDatatable
    tags:
        - { name: sg.datatable.view }
```

The parent service definition would look like this:

```
sg.datatable.abstract:
    abstract: true
    arguments:
        - "@security.authorization_checker"
        - "@security.token_storage"
        - "@twig"
        - "@translator.default"
        - "@router"
        - "@doctrine.orm.entity_manager"
        - "%sg_datatables.datatable.templates%"
```

Also the CompilerPass could be removed completely.
