### ISSUE TITLE
doesn't work at all :/

### ISSUE THREAD

**Issue by Ispolin08** [stwe/DatatablesBundle#347]
Hello. When I run composer add as described here, It's add "sg/datatablesbundle": "^0.10.0" tocomposer.json. 
After all I have 
The parent definition "sg_datatables.datatable.abstract" defined for definition "app.datatable.post" does not exist.
error.
As you understand there is no sg_datatables.datatable.abstract in 0.10.0 version.

**Comment by Ispolin08** [comment]
Also if i change version to master it will come, but still no work by same reason :/

**Comment by Ispolin08** [comment]
If i change version to master it's will not work because datatable_render will be undefined (in twig)

**Comment by stwe** [comment]
https://github.com/stwe/DatatablesBundle/blob/v0.10/Resources/doc/installation.md

clear your cache, install v0.10

this is the correct service definition:

```
app.datatable.post:
    class: AppBundle\Datatables\PostDatatable
    tags:
        - { name: sg.datatable.view }
```
