### ISSUE TITLE
change language 

### ISSUE THREAD

**Issue by licarigianluca** [stwe/DatatablesBundle#478]
Hi,
I'm using this bundle but I cannot find a way to change Datatables language. There is an option section but how can I put there this information?

When I'm using jquery Datatables I set the language this way:

 $('#tableId').DataTable(
                {

                    "language": {
                        "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Italian.json"
                    },
                  .....

How can I pass this information inside the Datatable build class?

thx

**Comment by witzkito** [comment]
I have my datatable in spanish using this 
```
# app/config/config.yml
framework:
    translator:      { fallback: [es] }
    default_locale:  "es"
```

But, a better way is in documentation of this bundle, sector installation:

```
# app/config/config.yml
framework:
    translator: { fallbacks: ["%locale%"] }

    # ...

    default_locale: "%locale%"
```
