### ISSUE TITLE
Sonata Media Image

### ISSUE THREAD

**Issue by xmon** [stwe/DatatablesBundle#503]
I've a entity relationed with Sonata Media Entity:
```php
    //...
    /**
     * @ORM\OneToOne(targetEntity="Application\Sonata\MediaBundle\Entity\Media",cascade={"remove", "persist"}, orphanRemoval=true), 
     * @ORM\JoinColumn(name="image_id", referencedColumnName="id")
     */
    private $image;
    //...
```

How can I use it on `columnBuilder`?

for now I do it this way:

```php
    //...
        $this->columnBuilder
            ->add('image.providerReference', 'image', array(
                'title' => 'Image',
                'relative_path' => "uploads/media/news/0001/02/",
                'imagine_filter' => 'news_list_dashboard_thumb',
                'imagine_filter_enlarged' => 'news_list_dashboard_large',
                'holder_url' => 'https://placehold.it',
                'holder_width' => '65',
                'holder_height' => '65',
                'enlarge' => true
            ))
    //...
```
but `relative_path `is dinamic, and could change.

thanks a lot

**Comment by oidnus** [comment]
+1

**Comment by oidnus** [comment]
I create very ugly solution but work :D 

1. Inject ProviderImage to datatable
```
    datatable.admin_network_site:
        class: Mediapilot\NetworkBundle\Datatables\Admin\NetworkSiteDatatable
        parent: sg_datatables.datatable.abstract
        calls:
            - [setProviderImage, ['@sonata.media.provider.image']]
```
2. In Datatables create method 
```
  public function setProviderImage($providerImage)
    {
        $this->providerImage = $providerImage;
    }

```
3. Add column 
```
 ->add('image.providerReference', 'column',[
                'title' => 'image',
                'visible' => true
            ])
```
4. Use line formater 
```
Public function getLineFormatter()
    {

        $formatter = function($line){
            if (isset($line['image']['id'])){
                $media = $this->em->getRepository('ApplicationSonataMediaBundle:Media')->find($line['image']['id']);
                $line['image']['providerReference'] = "<img src='".$this->providerImage->generatePublicUrl($media, 'default_small')."' alt=''>";
            }

            return $line;
        };

        return $formatter;
    }
```
