### ISSUE TITLE
filtering non visible column

### ISSUE THREAD

**Issue by versh23** [stwe/DatatablesBundle#554]
```
            ->add('uid', 'column', [
                'title'         => 'UID',
                'visible'       => false,
                'searchable'    => true,
                'filter'        => [
                    'text', [
                        'search_type' => 'eq',
                        'class'       => 'form-control',
                    ],
                ],
            ])
```

```
sg_datatables:
    datatable:
        query:
            search_on_non_visible_columns: true
```

after change input theare no ajax request
but in global searchbox it works
