### ISSUE TITLE
Importing template files

### ISSUE THREAD

**Issue by atouzard** [stwe/DatatablesBundle#569]
Hello,

I have a problem with the resource files of the bundle, as you can see in the picture linked bellow it would seems like the translation files are not imported properly, even after an 'assets:install'

do you have a solution ?

picture : http://i.imgur.com/CV4ZTDS.png

**Comment by stwe** [comment]
```
framework:
    translator: { fallbacks: ["%locale%"] }

    # ...

    default_locale: "%locale%"
```
