### ISSUE TITLE
Image Column with LiipImagineBundle Filter

### ISSUE THREAD

**Issue by felix-goecking** [stwe/DatatablesBundle#739]
Hi,
we are using an image column with a filter for thumbnails. As suggested we use the LiipImagineBundle in combination with OneUpFlysystem. OneFlySystem is for local development configured to store the files on local filesystem. Now the problem is the following:

Flysystem is configured to store images in "/web/uploads/media":
```` yaml
oneup_flysystem:
    adapters:
        image_adapter:
            local:
                directory: "%kernel.root_dir%/../web/uploads/media"
    filesystems:
        image_filesystem:
            adapter: image_adapter
            mount:   image_filesystem
````

 The imagine bundle uses the flysystem as adapter and loader:
```` yaml
liip_imagine:
    loaders:
        image_files:
            flysystem:
                filesystem_service: oneup_flysystem.image_filesystem_filesystem

    resolvers:
        image_files:
            flysystem:
                filesystem_service: oneup_flysystem.image_filesystem_filesystem
                root_url:           "%image_base_url%"
````
The filter is also set to use the image_file cache and data loader. Now when i set up the column in the datatable I need to apply a relative path to the image. This would be "/uploads/media". But using this the imagine bundle is not able to find the file, because it appends the relative path to the flysystem path. The imagine bundle can resolve the image correctly by only providing the image name without the relative path.

I don't know if it's a bug in this bundle or in the Liip Imagine bundle or if there is some more configuration to be done. But maybe someone has an idea how to fix it.
