### ISSUE TITLE
individual filtering

### ISSUE THREAD

**Issue by locs31** [stwe/DatatablesBundle#88]
Hi how can i place individual filtering input in thead instead of tfoot?
Thanks ;)

**Comment by DarekTw** [comment]
use css, example
```css
.dataTables_scroll {
    position: relative;

    .dataTables_scrollHead{
        padding-bottom: 42px;
    }

    .dataTables_scrollFoot{
        position: absolute;
        top: 43px;
    }
}
```
