### ISSUE TITLE
Autowire problem since 1.2 because of $translator

### ISSUE THREAD

**Issue by ITtoponline** [stwe/DatatablesBundle#945]
As $translator has no type-hint anymore in the AbstractDatatable class, I get an error when defining my Datatable like that

This is a datatable.yaml file imported in services.yaml
```
services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: true

  App\Datatables\UserDatatable:
    parent: sg_datatables.datatable.abstract
    autowire: true
    autoconfigure: false
    public: true
```

Well it says that $translator has no type-hint and should be configured explicitally.
